# Generated by Django 5.0.6 on 2026-05-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_caja_aperturacaja_movimientocaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PAGADA', 'Pagada'), ('ESPERA', 'Espera'), ('ANULADA', 'Anulada'), ('DEVUELTA', 'Devuelta')], default='PAGADA', max_length=20),
        ),
    ]
